### ISSUE TITLE
Installation build wheel error

### ISSUE THREAD

**Issue by jhogg11** [mlysy/kalmantv#2]
Hi, I wanted to try this package to hopefully get a speed improvement over similar Python libraries and am running into an issue with installation.  I followed the steps from the README file:

```
git clone https://github.com/mlysy/kalmantv
cd kalmantv
pip install .
```

And am getting this error on the install command:
```
DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Processing /Users/me/Downloads/kalmantv
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/me/.pyenv/versions/3.8.3/bin/python3.8 /Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/g1/0pjsd_bs24jgccrd6g0lzfvc0000gn/T/tmpxmrdlgnk
       cwd: /Users/me/Downloads/kalmantv
  Complete output (6 lines):
  running egg_info
  writing kalmantv.egg-info/PKG-INFO
  writing dependency_links to kalmantv.egg-info/dependency_links.txt
  writing requirements to kalmantv.egg-info/requires.txt
  writing top-level names to kalmantv.egg-info/top_level.txt
  error: package directory 'eigen-3.3.7' does not exist
  ----------------------------------------
WARNING: Discarding file:///Users/me/Downloads/kalmantv. Command errored out with exit status 1: /Users/me/.pyenv/versions/3.8.3/bin/python3.8 /Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/g1/0pjsd_bs24jgccrd6g0lzfvc0000gn/T/tmpxmrdlgnk Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/me/.pyenv/versions/3.8.3/bin/python3.8 /Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/g1/0pjsd_bs24jgccrd6g0lzfvc0000gn/T/tmpxmrdlgnk Check the logs for full command output.
```
I tried adding `--use-feature=in-tree-build` from the deprecation warning but still got the error (without the initial warning).

I saw a number of suggestions such as using `pip install --upgrade pip setuptools wheel`, but nothing is doing the trick.  I would guess that this has a simple fix but this stuff is a little over my head and I don't want to break anything else.  Any ideas?

**Comment by WillDaSilva** [comment]
Seems like the installation instructions are missing instructions to download the Eigen library, and make it available under the project's root directory under the name `eigen-3.3.7`.

**Comment by mlysy** [comment]
This is embarrassing...we went through all the trouble of creating [**eigenpip**](https://pypi.org/project/eigenpip/), a wrapper to a recent version of Eigen on PyPi, so that users wouldn't need to install Eigen themselves. But then we forgot to update **kalmantv** accordingly!  In any case, it's fixed now.  By the way, if you have installed a newer version of Eigen, you can install **eigenpip** to link to it instead of the version it comes packaged with.
